DROP TABLE IF EXISTS user;

CREATE TABLE user (
  uid INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  last VARCHAR(250) NOT NULL
);

INSERT INTO user (name, last) VALUES
 ('Billie', 'Holiday'),
     ('Sarah', 'Vaughan'),
     ('Ella', 'Fitzgerald'),
     ('Nat King', 'Cole'),
     ('Louis', 'Armstrong'),
     ('Nina', 'Simone'),
     ('Dinah', 'Washington'),
     ('Frank', 'Sinatra'),
     ('Carmen', 'McRae'),
   ('Johnny', 'Hartman'),
   ('Etta', 'Jones'),
   ('Tony', 'Bennet'),
   ('Ernestine', 'Anderson'),
   ('Betty', 'Carter'),
   ('Diana', 'Krall'),
   ('Cassandra', 'Wilson'),
   ('Shirley', 'Horn'),
   ('Blossom', 'Dearie'),
   ('Nancy', 'Wilson'),
   ('Abbey', 'Lincoln'),
   ('Astrud', 'Gilberto'),
   ('Chet', 'Baker'),
   ('Billy', 'Eckstine'),
   ('Peggy', 'Lee'),
   ('Chris', 'Connor'),
   ('June', 'Christy'),
   ('Etta', 'James'),
   ('Freddy', 'Cole'),
   ('Ray', 'Charles'),
   ('Harry', 'Connick Jr'),
   ('Natalie', 'Cole'),
   ('Lee', 'Wiley'),
   ('Annie', 'Ross'),
   ('Jon', 'Hendricks'),
   ('Michael', 'Buble'),
   ('Mildred', 'Bailey'),
   ('Betty', 'Roche'),
   ('Mel', 'Torme'),
   ('Jeri', 'Southern'),
   ('Diane', 'Schuur'),
   ('Rosemary', 'Clooney'),
   ('Mark', 'Murphy'),
   ('Chaka', 'Khan'),
   ('Helen', 'Merril'),
   ('Carol', 'Sloane'),
   ('Dee Dee', 'Bridgewater'),
   ('Mary', 'Stallings'),
   ('Gloria', 'Lynne'),
   ('Jimmy', 'Rushing'),
   ('Lena', 'Horne'),
   ('Eartha', 'Kitt'),
   ('Al', 'Jarreau'),
   ('Ricki Lee', 'Jones'),
   ('Diane', 'Reeves'),
   ('George', 'Benson'),
   ('Alberta', 'Hunter'),
   ('Nneena', 'Freelon'),
   ('Jack', 'Teagarden'),
   ('Norah', 'Jones'),
   ('Stacy', 'Kent'),
   ('Ethel', 'Waters'),
   ('Karrin', 'Alyson'),
   ('Sheila', 'Jordan'),
   ('Jo', 'Stafford'),
   ('Ella Mae', 'Morse'),
   ('Eddie', 'Jefferson'),
   ('Oscar', 'Brown Jr'),
   ('Joe', 'Williams'),
   ('Teddy', 'Grace'),
   ('Ernie', 'Andrews'),
   ('Jimmy', 'Scott'),
   ('Fats', 'Waller'),
   ('Cab', 'Calloway'),
   ('Leon', 'Thomas'),
   ('Cleo', 'Laine'),
   ('Maxine', 'Sullivan'),
   ('Vanessa', 'Rubin'),
   ('Louis', 'Jordan'),
   ('Aaron', 'Neville'),
   ('Lou', 'Rawls'),
   ('Marlena', 'Shaw'),
   ('Ivie', 'Anderson'),
   ('Ruth', 'Brown'),
   ('King', 'Pleasure'),
   ('Jimmy', 'Witherspoon'),
   ('John', 'Pizzarelli'),
   ('Johnny', 'Mercer'),
   ('Susannah', 'Mccorkle'),
   ('Madeleine', 'Peyroux'),
   ('Helen', 'Humes'),
   ('Lavern', 'Butler'),
   ('Connee', 'Boswell'),
   ('Bob', 'Dorough'),
   ('Jamie', 'Cullum'),
   ('Kevin', 'Mahogany'),
   ('Kurt', 'Elling'),
   ('Dr', 'John'),
   ('Big Joe', 'Turner');